## Numpy

In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
a = np.array([1,2,3,4])

In [13]:
b = np.array([0,.5,1,1.5,2])

In [9]:
a[0], a[1]

(1, 2)

In [10]:
a[0:]

array([1, 2, 3, 4])

In [11]:
a[1:3]

array([2, 3])

In [12]:
a[1:-2]

array([2])

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [16]:
b[[0,2,-1]]

array([0., 1., 2.])

### 1.Array Type

In [17]:
a.dtype

dtype('int32')

In [18]:
b.dtype

dtype('float64')

In [8]:
np.array([1,2,3,4], dtype= np.float64)

array([1., 2., 3., 4.])

In [7]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [9]:
c = np.array(['a','b','c'])

In [10]:
c.dtype

dtype('<U1')

In [12]:
d = np.array([{'a':1},sys])

In [13]:
d.dtype

dtype('O')

### 2.Dimension and Shapes

In [14]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [16]:
A.shape

(2, 3)

In [17]:
# one vertical, one horizontal, 2 dimension
A.ndim

2

In [19]:
A.size

6

In [23]:
B = np.array([
    [
        [12,11,10],
        [9,9,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [24]:
B

array([[[12, 11, 10],
        [ 9,  9,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [25]:
B.shape

(2, 2, 3)

In [26]:
#3 dimension
B.ndim

3

In [27]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python onjects:

In [32]:
C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [33]:
C.dtype

dtype('float64')

In [37]:
C.shape

(1, 0)

In [35]:
C.size

0

### 3.Indexing and Slicing of Matrices

In [38]:
# suqare matrix
A = np.array([
#    0 1 2
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
])

In [39]:
# dimension 1 = row
A[1]

array([4, 5, 6])

In [40]:
# A[dimension1][dimension2]
# dimension 2 = column
A[1][0]

4

In [ ]:
# A[d1,d2,d3,d4]
A[1,0]

In [41]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# :2 = slice until 2 but not include 2
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [43]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [44]:
A[:2,2:]

array([[3],
       [6]])

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
#substitute row 1 by each column
A[1] = np.array([10,10,10])

In [47]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [48]:
#susbttitute all row 2 into 99
A[2] = 99

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### 4.Summary Statistic

In [50]:
a = np.array([1,2,3,4])

In [51]:
a.sum()

10

In [52]:
a.mean()

2.5

In [53]:
a.std()

1.118033988749895

In [54]:
a.var()

1.25

In [55]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [56]:
A.sum()

45

In [57]:
A.mean()

5.0

In [58]:
A.std()

2.581988897471611

In [59]:
# axis 0 = dimension1/row
A.sum(axis=0)

array([12, 15, 18])

In [60]:
# axis 1 = dimension2/column
A.sum(axis=1)

array([ 6, 15, 24])

In [61]:
A.mean(axis=0)

array([4., 5., 6.])

In [62]:
A.mean(axis=1)

array([2., 5., 8.])

In [63]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [64]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### 5.Broadcasting and Vectorized Operation

In [65]:
a = np.arange(4)

In [66]:
a

array([0, 1, 2, 3])

In [67]:
a + 10

array([10, 11, 12, 13])

In [68]:
a * 10

array([ 0, 10, 20, 30])

In [69]:
a

array([0, 1, 2, 3])

In [70]:
#make new array as base array
a += 100

In [71]:
a

array([100, 101, 102, 103])

In [72]:
l = [0,1,2,3]

In [73]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [74]:
a = np.arange(4)

In [75]:
a

array([0, 1, 2, 3])

In [76]:
b = np.array([10,10,10,10])

In [77]:
a+b

array([10, 11, 12, 13])

In [78]:
a*b

array([ 0, 10, 20, 30])

### 6.Boolean Arrays

In [80]:
a = np.arange(4)

In [81]:
a

array([0, 1, 2, 3])

In [83]:
#python method selection
a[0], a[-1]

(0, 3)

In [82]:
#multi index selection
a[[0, -1]]

array([0, 3])

In [84]:
#boolean array selection
a[[True, False, False, True]]

array([0, 3])

In [85]:
# is a larger and equal than 2?
a >=2

array([False, False,  True,  True])

In [86]:
# selection base on boolean array condition
a[a >=2]

array([2, 3])

In [87]:
a.mean()

1.5

In [88]:
a[a > a.mean()]

array([2, 3])

In [89]:
# ~ = not
a[~(a > a.mean())]

array([0, 1])

In [90]:
# | = Or
a[~(a == 0) | (a == 1)]

array([1, 2, 3])

In [91]:
# & = and
# % = ???
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [92]:
A = np.random.randint(100, size=(3,3))

In [93]:
A

array([[83, 61, 86],
       [72, 76, 35],
       [31, 14, 91]])

In [94]:
A[np.array([
    [True,False,True],
    [False,True,False],
    [True,False,True]
])]

array([83, 86, 76, 31, 91])

In [95]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [96]:
A[A>30]

array([83, 61, 86, 72, 76, 35, 31, 91])

### 7.Linear Algebra

In [97]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [98]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [99]:
# .dot = multiplying matrixes?
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [100]:
# @ = multiplying matrixes?
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [101]:
# .T = transponse the matrix
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [102]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### 8.Performance

In [111]:
l = list(range(100000))

In [112]:
a = np.arange(100000)

In [113]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1.01 ms


216474736

In [114]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 18.6 ms


333328333350000

### 9.Useful Numpy Functions

#### random

In [ ]:
np.random.random(size=2)

In [ ]:
np.random.normal(size=2)

In [ ]:
np.random.rand(2,4)

#### arange

In [ ]:
np.arange(10)

In [ ]:
np.arange(5,10)

In [ ]:
np.arange(0,1,.1)

#### reshape

In [115]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5,2)

#### linspace

In [ ]:
np.linspace(0,1,5)

In [ ]:
np.linspace(0,1,20)

In [ ]:
np.linspace(0,1,20, False)

#### zeros, ones, empty

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((3,3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3,3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2,2))